export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_NEW_ITEM: 'ADD_NEW_ITEM',
  INCREASE_CART_ITEM_QUANTITY: 'INCREASE_CART_ITEM_QUANTITY',
  DECREASE_CART_ITEM_QUANTITY: 'DECREASE_CART_ITEM_QUANTITY',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
};
